### ISSUE TITLE
Missed version update for FFmpeg

### ISSUE THREAD

**Issue by estshorter** [regro/cf-scripts#1082]
The autotick-bot missed the following update.

- [FFmpeg](https://github.com/conda-forge/ffmpeg-feedstock/blob/master/recipe/meta.yaml): v4.3.1

According to the "[run_versions_update](https://app.circleci.com/pipelines/github/regro/circle_worker/17141/workflows/728c67c8-9f16-4e6d-9352-15504257ec38/jobs/34750)" task in CircleCI, checking updates returns false.

Note:
This is different from #1072, because the bot tries to check updates.

**Comment by CJ-Wright** [comment]
Thank you very much for the bug report! (This has been the most helpful by far!)

I think I see the issue here. For packages from servers that we don't support via API (PyPI, GitHub, CRAN (I think)) we try a brute force approach by bumping the version number and seeing if that exists on the server. Because FFMpeg didn't adhere to semver (it dropped the last number) we're running into issues. The bot will bump the last number, but it doesn't know that there should be a third number in the version so it just bumps the minor number, which results in no new versions being found.

I'm not exactly certain what the correct path forward is here, we could make the fix in the FFmpeg feedstock, adding some jinja2 to promote the version to 4.3.0, and the bot should catch that since it uses the version in the version key to run this update. We could also put some logic into the version update code, but I think this is a bit more tenuous since some projects genuinely don't use full three number semver. I think the best outcome (although unlikely) would be for FFmpeg to use semver properly.

**Comment by estshorter** [comment]
Thank you for your clear explanation!
I'll create a PR for the FFmpeg feedstock.
