### ISSUE TITLE
Data model for PR json

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#1175]
It would be good to have a data model for the elements from pr json we actually use. We might consider using Cerberus if we don't want to use DataClasses directly. This would require a refactor of existing code, but would enable us to use type hinting functionality better.

**Comment by CJ-Wright** [comment]
The culmination of this would be a function that trims PR json down to the needed fields when the PR is closed.

**Comment by mariusvniekerk** [comment]
Could also use pydantic if we want some nice baked in serializability

**Comment by beckermr** [comment]
@lguo52 This issue is about cutting down on the PR json size.

You can see an example blob here: https://github.com/regro/cf-graph-countyfair/blob/master/pr_json/196743621.json

A few steps here to be concrete.

1. **determine which keys we need**
2. **figure out how to update the PR status with only the keys from 1**: This step will need to use the ETag from github. @CJ-Wright did some testing here.
3. **put a shim in the code**: make a PR onto regro/cf-scripts that starts writing only the smaller json blobs, but is able to handle reads of the bigger ones too 
4. **cleanout graph data**: once 3 is working ok, go ahead and make a PR to migrate all of the old PR json to the new smaller format.
5. **remove shim**: much much later we can remove the shim once everything here is complete

**Comment by beckermr** [comment]
Keys we need:
 - labels
 - etag
 - id
 - state
 - mergeable_state
 - html_url
 - created_at
 - head
 - base
 - merged_at
 - updated_at
 - number

**Comment by beckermr** [comment]
Looks like we can get a factor of 50x in storage just from keeping the keys above.

**Comment by beckermr** [comment]
This is done.
