### ISSUE TITLE
Using Grayskull for update PRs

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#1471]
Am curious how we might start to leverage grayskull in update PRs. This would really help to capture requirement updates, metadata changes (like licensing), etc. that show up in version updates. Also would help reduce errors due to early merges of update PRs. Curious what would be needed for this change

**Comment by beckermr** [comment]
Cc @CJ-Wright

**Comment by jakirkham** [comment]
cc @marcelotrevisani

**Comment by CJ-Wright** [comment]
In my opinion the pypi metadata (mostly requirements) has not been accurate enough to use it directly. If we could source better requirements metadata I think using grayskull would be great.

There was some preliminary work on understanding the metadata mismatch here: https://github.com/regro/cf-graph-countyfair/tree/master/audits (It most likely needs to be revived/revamped since it could be a bit out of date).

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by jakirkham** [comment]
Thanks for the context CJ! 😄 This is good to know.

Would it be possible to consider it as something feedstocks could opt-in to? Perhaps with a flag in `conda-forge.yml`?

For some simple cases feedstock maintainers may know the metadata is fairly reliable. Additionally it may enable more feedstocks to consider auto-merge PRs (perhaps after a few test runs to gain more confidence).

**Comment by beckermr** [comment]
cc @mariusvniekerk who added something similar for noarch wheels

**Comment by jakirkham** [comment]
cc @ocefpaf (who may have interest in this as well)

**Comment by CJ-Wright** [comment]
As an aside I think it would be fine to update non-requirement metadata. I would be curious to see the mismatch with the existing metadata.

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by marcelotrevisani** [comment]
``grayskull`` does not look just for the PyPI metadata, it depends on the scenario, in fact it tries to get some data like the licence from there. Because, nowadays PyPI is following what is the ``sdist`` package, so basically when you are saying that you do not trust in the PyPI metadata in fact you do not trust in the maintainers of the project, as that is just replicating what is their project metadata.

with the new feature added by @ForgottenProgramme , now ``grayskull`` can generate the recipes looking for github releases, so, all the metadata will be extracted from the repository. 

on top of that, if ``grayskull`` does not find the specification for the licence it tries to search for the licence file when it finds it, it does a fuzzy comparison to see which licence that might be

**Comment by marcelotrevisani** [comment]
but that is doable, it would be nice to just have an webservice or maybe a github action to trigger the process.

I was working on this other project https://github.com/marcelotrevisani/souschef to easily manipulate the recipes, I still need to do a couple of adjustments regarding the jinja stuff. My idea is to add that to ``grayskull`` so it will be simple to manipulate the yaml

**Comment by marcelotrevisani** [comment]
It seems @sgbaird have being using ``grayskull`` with ``souschef`` to create a pipeline for his needs. it is possible to do something similar as well.

https://github.com/marcelotrevisani/souschef/issues/32

**Comment by CJ-Wright** [comment]
> you do not trust in the PyPI metadata in fact you do not trust in the maintainers of the project

Personally, I find that authors are in rather a tight spot when deciding what their project's dependencies are, it generally requires a much greater knowledge of the ecosystem than I think would be a reasonable expectation. Getting pins correct is particularly difficult, since it would require foreknowledge of how dependencies may change their code and versions. 

In my opinion it is the author's job to write the code and the ecosystem's job to figure out how that code fits into the bigger picture. This is especially true since different packaging ecosystems could have different requirements or specifications.

For example: https://github.com/conda-forge/ipython-feedstock/issues/127, https://github.com/facebook/prophet/blob/360d294dbce0bbc9f1e262b77488cdf52f3b8fd6/python/requirements.txt#L3 (in this example pystan changed the name of the library in their 3.0 version, breaking every import)

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by marcelotrevisani** [comment]
> > you do not trust in the PyPI metadata in fact you do not trust in the maintainers of the project
> 
> Personally, I find that authors are in rather a tight spot when deciding what their project's dependencies are, it generally requires a much greater knowledge of the ecosystem than I think would be a reasonable expectation. Getting pins correct is particularly difficult, since it would require foreknowledge of how dependencies may change their code and versions.
> 
> In my opinion it is the author's job to write the code and the ecosystem's job to figure out how that code fits into the bigger picture. This is especially true since different packaging ecosystems could have different requirements or specifications.
> 
> For example: [conda-forge/ipython-feedstock#127](https://github.com/conda-forge/ipython-feedstock/issues/127), https://github.com/facebook/prophet/blob/360d294dbce0bbc9f1e262b77488cdf52f3b8fd6/python/requirements.txt#L3 (in this example pystan changed the name of the library in their 3.0 version, breaking every import)
> 
> I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

I agree, it is difficult and we can find that people usually forgot to update it, but it is also problematic to totally avoid what the authors/maintainers are doing you know? But one thing we can consider is to suggest to add new packages and/or update lower bounds constrains. I believe that will already improve a lot of aspects.

In terms of the licence itself, I think it does not change much and it can do a good job in most cases.

**Comment by ocefpaf** [comment]
I've been using grayskull 100% to update deps and moving away from automerge. We are producing tons of broken pkgs while the metadata for it is there and we are not using. TL;DR it is not a matter of "opinion on the metadata" it is a matter of numbers. A few bad metadata is forcing us to manually update tons of pkgs. Also, the way things are, automerge is pretty much a risk.

**Comment by wshanks** [comment]
Should this have been closed by https://github.com/regro/cf-scripts/pull/1503?

**Comment by ocefpaf** [comment]
> Should this have been closed by #1503?

Yep. There is always extra work to be done but the essence of this issue is already implement and, if we want to continue this, we should open new ones with more specific info.
