### ISSUE TITLE
[Errno 28] No space left on device

### ISSUE THREAD

**Issue by justcalamari** [regro/cf-scripts#164]
The bot is running into this error and stops after a few PRs.

**Comment by CJ-Wright** [comment]
example: https://api.travis-ci.org/v3/job/386597735/log.txt

**Comment by scopatz** [comment]
Here is how you only pull HEAD: https://stackoverflow.com/questions/1209999/using-git-to-get-just-the-latest-revision

**Comment by CJ-Wright** [comment]
I someone ends up fixing this please make the changes to the `.travis.yml` to https://github.com/regro/cf-scripts/blob/master/travis_template.yml and then use the https://github.com/regro/cf-scripts/blob/master/configure_workers.xsh to properly configure the workers.

The worker configuration script may need to have the CI no-op although I don't know what the travis cron job will do if we never build on the repo directly. Otherwise we need to stop the workers since they will have all been triggered simultaneously which could end up with a very confused graph.

**Comment by isuruf** [comment]
You just need to change https://github.com/regro/cf-scripts/blob/master/setup.sh, no need to configure the workers.

**Comment by justcalamari** [comment]
It looks like this was solved by #170

**Comment by CJ-Wright** [comment]
It seems that we may be facing this again (although I'm not certain why, yet). I think it may be due to a leak in `tmp` or in the main folder. I'll try to add some diagnostics (`ls`, `du -hs`) to understand what is going on.

**Comment by justcalamari** [comment]
It looks like since `@(os.path.join('/tmp', dir) + '/*)` is a string, `du` is looking for a file named `*` explicitly rather than using it as a wildcard.

**Comment by CJ-Wright** [comment]
Yea I fixed it to use indir so that should be fixed now?

**Comment by CJ-Wright** [comment]
seemed to be fixed (not a long term fix, but works for now)
