### ISSUE TITLE
Bot didn't update the SHA

### ISSUE THREAD

**Issue by scottbelden** [regro/cf-scripts#184]
Firstly, just want to say that I really like the regro-autotick-bot. However, a [recent PR](https://github.com/conda-forge/fastavro-feedstock/pull/38/files) it created only updated the version number and not the SHA which resulted in failures in those CI tests due to the mismatch.

You can see from some [previous merged PRs](https://github.com/conda-forge/fastavro-feedstock/pulls?q=is%3Apr+is%3Aclosed) that in the past it created the correct change, but this time it messed up for some reason.

I can easily fix this if it was just a one time fluke, but I wanted to post this in case there was some underlying issue that you should be aware of.

Once again, thanks for the bot!

**Comment by scopatz** [comment]
Thanks for reporting @scottbelden! This definitely should have been picked up.  @justcalamari can you take a look please? Thanks!

**Comment by justcalamari** [comment]
This is happening because the `url` key is indented by 4 spaces instead of 2, which the bot doesn't look for after merging #163. Once #182 is finished I think this will be fixed.

**Comment by justcalamari** [comment]
@scottbelden I think the only way of doing this is to change the attributes the bot sees for fastavro so it thinks there is no PR open. This will cause the bot to update the recipe and PR again. Creating the PR should fail since a PR already exists for the branch, but the changes will be pushed. I can do this once #182 goes in.

**Comment by justcalamari** [comment]
It looks like this was fixed, so I'm closing this issue.
