### ISSUE TITLE
Python 3.12 build fails

### ISSUE THREAD

**Issue by dofuuz** [regro/cf-scripts#1851]
Python 3.12 build fails on https://github.com/conda-forge/soxr-python-feedstock/pull/16 .

```
The reported errors are:
- Encountered problems while solving:
-   - nothing provides _python_rc needed by python-3.12.0rc3-rc3_h2628c8c_1_cpython
```

Full log:
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=796900&view=logs&j=7df5a329-fcdb-5857-5720-a5dae94c0641&t=67fc0302-7ecf-51cb-2fd0-391a1258793e&l=81

**Comment by beckermr** [comment]
This issue isn't about the bot, but is instead specific to the feedstock, so it should remain there. 

@xhochy any ideas?

**Comment by xhochy** [comment]
This is a misleading error message. Sadly mamba always backtracks to the Python 3.12 rc but the actual cause is something different. Please try solving the environment manually using a new version of mamba with the new resolver hints. This should give you a better error message. In the case of poetry it is actually that an older version of dulwich needs to bw rebuilt for 3.12.

**Comment by beckermr** [comment]
Which version of mamba do we need? We can pin the bot to use at least that one.

**Comment by dofuuz** [comment]
Removing channel_sources and rerendering somehow solved the problem... I don't know why.
