### ISSUE TITLE
`aarch64andppc64leaddition` lumping lots under `pyqt` (even when unused)

### ISSUE THREAD

**Issue by jakirkham** [regro/cf-scripts#2275]
It appears the bot is lumping lots of feedstocks as dependent on `pyqt` for the `aarch64andppc64leaddition`. However many of them don't even use `pyqt`

For example `psutil` is on the list even though it only depends on `python`

Here's a screenshot:

<img width="1840" alt="Screenshot 2024-03-18 at 3 15 23 PM" src="https://github.com/regro/cf-scripts/assets/3019665/962abfa2-9da5-4c89-9b75-be0f176ddbb7">

Do we know what is causing this?

**Comment by beckermr** [comment]
Oh that's fun. We'd have to inspect the graph data by hand.

**Comment by jakirkham** [comment]
Yeah it's interesting as several of these were already migrated ( like in the case of `psutil` this was quite some time ago https://github.com/conda-forge/psutil-feedstock/pull/35 )

So it is interesting to see these are now awaiting parents

**Comment by beckermr** [comment]
The graph can get weird cycles and stuff due to mutexes etc. I'm sure we'll figure it out once we have a chance to look.

**Comment by beckermr** [comment]
OK this is now fixed. For the record, the issue was

 - flit vs flit-core (flit is the CLI bit and flit-core is the build tool, but both are in the same feedstock)
 - an erroneous dependence on `rich` in `setuptools_scm`

I fixed the first item in the bot by special casing it the bot to force the feedstock to move with flit-core for now. The second I fixed directly in the setuptools_scm feedstock.

**Comment by jakirkham** [comment]
Thanks Matt! 🙏
