### ISSUE TITLE
Refactor into atomic chunks

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#235]
It might be nice to have this system be more atomic. Currently we play a very careful game keeping the cron jobs from colliding (helped by Travis' 50 min timeout and large gaps between runs).

To make the system more atomic we need two major adjustments:
1. Create a queue for the migrations
1. Create a folder of json files which are to be added to the graph.

The basic idea for the actual migration part is:
1. Read next item in queue which includes everything needed to perform the migration
1. Perform the migration
1. Put the extra data (PR information) into a json file in a folder
1. Pop the item off the queue
1. Push everything back

**Comment by mariusvniekerk** [comment]
We could just mark the file as completed and keep them forever.  
That is somewhat easier to deal with in a more atomic setting

**Comment by CJ-Wright** [comment]
For the rest of the bot its jobs are to:
1. Follow the migrator script but doing other things (getting upstream versions, current feedstocks, etc)
1. Collate the incoming data into a usable graph

**Comment by CJ-Wright** [comment]
Actually we could have the central control handle the pop stuff, since it will know if a PR went out since it needs to integrate the PRed information in.

**Comment by mariusvniekerk** [comment]
- each thing that would have generated a feedstock pr instead makes a file and writes it.  
- each of these pr templates should have a unique identifer
- a separate process(es) consumes these files and based on their id and undoneness state, makes a pr and updates the applicable state file.

Since nothing is reading and creating the same file at the same time we can succeed at pushing these changes, though if we fail due to upstream being different we just need to do a `git pull --rebase` and retry the push a few times

**Comment by CJ-Wright** [comment]
I think this mostly exists via CFEP9. We could run more commits/deploys to truly make this atomic but I think our current level is reasonable.
