### ISSUE TITLE
SHA256 mismatch

### ISSUE THREAD

**Issue by arsenovic** [regro/cf-scripts#327]
a git tagged auto-built conda recipe looks good here, 
https://github.com/conda-forge/clifford-feedstock/pull/3

but fails circleci with a sha256 mismatch
https://circleci.com/gh/conda-forge/clifford-feedstock/10

??

**Comment by CJ-Wright** [comment]
The github based tarballs are usually stable, but if you delete a branch on the main repo the checksums can move. If you are the release manager for this code I'd suggest that you release your own tarballs along side the github tarballs so that they are stable. In the meantime, I'd push up a PR to fix the checksum.

**Comment by arsenovic** [comment]
ok thank you.

**Comment by CJ-Wright** [comment]
On a side note if you are the release manager [rever](https://regro.github.io/rever-docs/) will do this for you automatically.

**Comment by arsenovic** [comment]
ok, thanks for the tip, ill look into it.
