### ISSUE TITLE
Bot gets wrong SHA

### ISSUE THREAD

**Issue by glyg** [regro/cf-scripts#448]
Hi,
First, thanks for the work, that bot is neat, as is the whole conda-forge.

It might be related to #184 (or not), but on the last 2 releases of tyssue, regro-autotick failed to update the sha256 sum correctly. Here is the last PR:
https://github.com/conda-forge/tyssue-feedstock/pull/15

I can fix the sum easily enough, but maybe there's an easy fix. There are multiple `source` entries in `conda.yml` so it might come from that, as the bot seems to assign the sha256 of the cgal source to the package source. 

```diff
  {% set name = "tyssue" %}
  {% set version = "0.3.0" %}
+ {% set sha256 = "fa30cb32ea32ebe5ebf27c9dc9728730cff224fca23242eb95edaf83727ef000" %}
+ {% set version = "0.3.1" %}
- {% set sha256 = "c4912a00e99f29ee37cac1d780d115a048743370b9329a2cca839ffb392f3516" %}
- {% set cgal_version = "4.13" %}
 {% set cgal_sha256 = "c4912a00e99f29ee37cac1d780d115a048743370b9329a2cca839ffb392f3516" %}
  {% set pb11_version = "2.2.4" %}
```

Thanks!

Guillaume

**Comment by scopatz** [comment]
Hi @glyg - I think that this is unrelated to #184. This is a separate issue, because you have multiple hashes all declared as jinja variables.  It might work if you instead move the hashes into the source section and get rid of the jinja variables.  Alternatively, we are always looking for PRs here!
