### ISSUE TITLE
eliminate PRed

### ISSUE THREAD

**Issue by CJ-Wright** [regro/cf-scripts#499]
Just use PRed_json everywhere. This will mean we only reference newer migrations and fixes some other issues we've been running into with the indices not being the same.

**Comment by CJ-Wright** [comment]
Steps to fix this:
1. Change how `migrators.Migrator.filter` works. Currently this looks at `attrs['PRed']`. This should be moved to `attrs['PRed_json']`. Note that `PRed_json` has an extra key (`PR`) which is not in the `frozen_to_json_friendly(self.migrator_uid(attrs))` which needs to be handled. (line 62)
1. Change how `migrators.Version.filter` works, again we look at `PRed` when we should look at `PRed_json` (line 305)
1. Change how `migrators.Rebuild.filter` works. (line 757)
1. `migrators.xsh` line 970
1. `make_graph.py` line 228 can be eliminated once we don't use `PRed` any more
1. `update_upstream_versions.py` line 308 needs to use `PRed_json` (and pull from the `PRed_json` data the version number (I'm not certain how this works currently)).
1. eliminate `auto_tick.xsh` line 565

For many of the things in `migrators.xsh` and other places where we're checking if `muid in attrs['PRed']` we most likely need to create a copy which doesn't have the `data` in it or have a way to exclude that from the search since none will match otherwise.

**Comment by xhochy** [comment]
From my understanding, we cannot get rid of `PRed` as it contains more information than `PRed_json`. For migrations where the migrator realises that no migrations is needed anymore (e.g. because a user has done it manually), we will not issue PRs and thus don't have an entry in `PRed_json`, still the data returned by the migrator will be recored in `PRed` so that we don't check the migrator on every walk through the graph.

See also #531 and #532

**Comment by CJ-Wright** [comment]
In this case we might consider having an empty `PRed_json` value for the given migration key. At that point `set(PRed) == set(PRed_json.keys())` modulo some super old PRs which were not tracked.
