### ISSUE TITLE
Use the installed CFP package instead of a git checkout

### ISSUE THREAD

**Issue by isuruf** [regro/cf-scripts#861]

**Comment by beckermr** [comment]
We should also just inject the time stamp into the yaml in the repo.

**Comment by CJ-Wright** [comment]
What do you mean "inject the time stamp"?

**Comment by beckermr** [comment]
Right now we copy the full migration file. With the files in pinnings and the new conda smithy, we only need a stub file in the repo. We don’t have to do this I suppose.

**Comment by CJ-Wright** [comment]
I'm not certain I agree with using the CFP package for the pinning migrations, this will produce many more versions of the CFP package with no demonstrable results for the package installers.

**Comment by beckermr** [comment]
well the ship has sailed on this already. The features are in conda build and the pinnings repo already. 

The issue with the current system is that it puts a local copy in the git repo. Updating this local copy for many thousands of feedstocks is really hard. By having the migrations always pull the latest from the pinnings package during rerenders, we can much more easily make edits. 

This is demonstrably better IMHO and is worth a few extra versions of the pinnings repo.

**Comment by CJ-Wright** [comment]
We could have pulled the current information from the pinning repo (rather than a local copy) without requiring it to be shipped in the package itself. The migrations folder is in the pinning repo for social reasons, it seemed liked a reasonable single source of truth for pinning decisions.

This seems like it hasn't sailed yet since this issue exists.

**Comment by CJ-Wright** [comment]
Also won't this still need rerenders across the stack if you make changes?

For instance if we change the version of a pin half way through we need to start again at the top to pull the new version into the file.

**Comment by CJ-Wright** [comment]
Sorry let me clarify a little better now that I'm not typing on a phone.

I understand why you would want to change a migration part way through and don't need to rerender everything (you fix it in the metadata patch itself).

The reason why the migrations folder was created in the pinning repo was mostly because people already associated the pinning repo with the pins so it was socially a natural place to put the migration folder, a one stop shop for pin setting and migration. I did not intend for that folder to get packaged. I don't see a ton of value from packaging the migration folder, users beyond the bot don't use those files and I don't think they make a lot of sense to be incorporated in an installable object.

I do think it adds complexity that will slow things down, since users (including the bot) will now need to update the meta.yaml in addition to making the migration yaml and all migrations will await for the pinning package to be built and synced to the CDN.

This approach doesn't add much in the way of a historical record either since we have a git backed source of truth for all the migrations. 

Overall I think it makes more sense to have the migrations folder be its own repo than to be packaged in the pinnings, especially as this would mean that we could run a CI against it to check migration quality and impact without having to run it along side our pinning package building CI system.

I am fine with the migration yaml files in the feedstocks themselves to be pointers back to the central migration yamls (although at that point we might consider just having one migration entity in the feedstocks as a key value store with names and timestaps, but that is an optimization for a later date).

**Comment by beckermr** [comment]
Yeah I see your point. I don’t think it actually matters much either way. The issue here iirc is that the python 38 migration needed a change for the pypy one. Note that until that migration is merged into the pinnings, we still rely on the yaml stored in each feedstock. Thus we wanted a global source. If you feel strongly about this, feel free to make PRs on the pinnings and smithy to pull from GitHub and to remove the migration files from the package. 

As it stands now we need to pull them from the package here in order to keep things in sync given the build times and CDN delays. Otherwise we will issue bad PRs.

**Comment by CJ-Wright** [comment]
In that case I'll try to fix smithy this weekend

**Comment by CJ-Wright** [comment]
On reflection, I think my efforts are better spent on other things, please feel free to put up a PR implementing this change if you would like.

**Comment by beckermr** [comment]
I'm more than happy to go the last mile here to make it all consistent!

**Comment by CJ-Wright** [comment]
If you could it would be great if you could update the migration creation PR so that the migration goes into effect when merged.

**Comment by beckermr** [comment]
What do you mean?

When a PR is merged on pinnings, the pinnings package gets rebuilt. Once the new pinnings version is available, then cf-scripts will pull the migration file and get to work. So I think this already happens? Or did I miss something?

**Comment by beckermr** [comment]
Or I should say, will happen once I address this issue.

**Comment by CJ-Wright** [comment]
Don't you need to update the version and build number?

**Comment by beckermr** [comment]
I am so lost @CJ-Wright sorry. Maybe we should do this on keybase for second.
